import { bootstrapApplication } from "@angular/platform-browser"
import { appConfig } from "./app/app.config"
import { AppComponent } from "./app/app.component"

import { addIcons } from "ionicons"
import {
  heart,
  add,
  search,
  closeCircle,
  eye,
  help,
  heartOutline,
  shareSocialOutline,
  chatbubbleOutline,
  bookmarkOutline,
  ellipsisHorizontalOutline,
  home,
  paperPlaneOutline,
  person,
  bookOutline,
  restaurantOutline,
  logOut,
  nutrition,
  bookmarkSharp,
  addCircleOutline,
  cartOutline,
  gridOutline,
  documentOutline,
  eyeOutline,
  eyeOffOutline,
  timeOutline,
  albumsOutline,
  pencilOutline,
  chevronDownOutline,
  notificationsOutline,
  grid,
  albums,
  bookmarks,
  bookmarksOutline,
  camera,
  closeCircleOutline,
  trashOutline,
  bookmark,
  cameraOutline,
  sendOutline,
  checkmark,
  checkmarkSharp,
  checkmarkDone,
  sunny,
  moon,
  radioButtonOn,
  cart,
  // Nuevos iconos para el chat
  chatbubbleEllipses,
  send,
  happyOutline,
  refreshOutline,
  alertCircle,
  ellipsisHorizontal,
} from "ionicons/icons"

addIcons({
  heart,
  home,
  person,
  add,
  search,
  closeCircle,
  eye,
  help,
  heartOutline,
  shareSocialOutline,
  chatbubbleOutline,
  bookmarkOutline,
  ellipsisHorizontalOutline,
  paperPlaneOutline,
  bookOutline,
  restaurantOutline,
  logOut,
  nutrition,
  bookmarkSharp,
  addCircleOutline,
  cartOutline,
  gridOutline,
  documentOutline,
  eyeOutline,
  eyeOffOutline,
  timeOutline,
  albumsOutline,
  pencilOutline,
  chevronDownOutline,
  grid,
  albums,
  bookmarks,
  bookmarksOutline,
  camera,
  closeCircleOutline,
  trashOutline,
  bookmark,
  cameraOutline,
  sendOutline,
  checkmark,
  checkmarkSharp,
  checkmarkDone,
  sunny,
  moon,
  radioButtonOn,
  notificationsOutline,
  cart,
  // Nuevos iconos para el chat
  chatbubbleEllipses,
  send,
  happyOutline,
  refreshOutline,
  alertCircle,
  ellipsisHorizontal,
})

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err))
